name: "Escape test"

on:
  workflow_dispatch:

jobs:
  escape-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ESCAPED=${{ toJSON(vars.ESCAPE_TEST) }}
          echo "PASSWORD=\"$ESCAPED\""
